# Generated by Django 3.0.5 on 2021-01-11 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_name', models.CharField(max_length=32, unique=True, verbose_name='资源名称')),
                ('Documentation', models.CharField(max_length=255, verbose_name='资源描述')),
                ('Library', models.CharField(max_length=128, verbose_name='引用库')),
                ('Variables', models.CharField(max_length=128, verbose_name='引用变量')),
                ('Scalar_Variables', models.CharField(max_length=128, verbose_name='普通变量')),
                ('List_Variables', models.CharField(max_length=128, verbose_name='列表变量')),
                ('Dict_Variables', models.CharField(max_length=128, verbose_name='字典变量')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
                ('Resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repository.Resource')),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suite_name', models.CharField(max_length=32, unique=True, verbose_name='套件名称')),
                ('Documentation', models.CharField(max_length=255, verbose_name='套件描述')),
                ('Suite_Setup', models.CharField(max_length=128, verbose_name='套件数据初始化')),
                ('Suite_Teardown', models.CharField(max_length=128, verbose_name='套件数据清理')),
                ('Test_Setup', models.CharField(max_length=128, verbose_name='用例数据初始化')),
                ('Test_Teardown', models.CharField(max_length=128, verbose_name='用例数据清理')),
                ('Test_Template', models.CharField(max_length=128, verbose_name='用例模版')),
                ('Test_Timeout', models.CharField(max_length=32, verbose_name='超时时间')),
                ('Force_Tags', models.CharField(max_length=32, verbose_name='项目标记')),
                ('Default_Tags', models.CharField(max_length=32, verbose_name='套件标记')),
                ('Library', models.CharField(max_length=128, verbose_name='引用库')),
                ('Variables', models.CharField(max_length=128, verbose_name='引用变量')),
                ('Scalar_Variables', models.CharField(max_length=128, verbose_name='普通变量')),
                ('List_Variables', models.CharField(max_length=128, verbose_name='列表变量')),
                ('Dict_Variables', models.CharField(max_length=128, verbose_name='字典变量')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
                ('Resource', models.ManyToManyField(to='repository.Resource')),
            ],
            options={
                'db_table': 'suite',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=32, unique=True, verbose_name='项目名称')),
                ('Documentation', models.CharField(max_length=255, verbose_name='项目描述')),
                ('Suite_Setup', models.CharField(max_length=128, verbose_name='项目数据初始化')),
                ('Suite_Teardown', models.CharField(max_length=128, verbose_name='项目数据清理')),
                ('Test_Setup', models.CharField(max_length=128, verbose_name='用例数据初始化')),
                ('Test_Teardown', models.CharField(max_length=128, verbose_name='用例数据清理')),
                ('Force_Tags', models.CharField(max_length=32, verbose_name='项目标记')),
                ('Library', models.CharField(max_length=128, verbose_name='引用库')),
                ('Variables', models.CharField(max_length=128, verbose_name='引用变量')),
                ('Scalar_Variables', models.CharField(max_length=128, verbose_name='普通变量')),
                ('List_Variables', models.CharField(max_length=128, verbose_name='列表变量')),
                ('Dict_Variables', models.CharField(max_length=128, verbose_name='字典变量')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
                ('update_time', models.DateTimeField(verbose_name='修改时间')),
                ('Resource', models.ManyToManyField(to='repository.Resource')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
