# Generated by Django 3.0.5 on 2021-01-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20210111_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='update_time',
            field=models.DateTimeField(null=True, verbose_name='修改时间'),
        ),
    ]
