# Generated by Django 3.0.5 on 2021-01-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20210111_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='Resource',
        ),
        migrations.AddField(
            model_name='resource',
            name='Resource',
            field=models.ManyToManyField(null=True, related_name='_resource_Resource_+', to='repository.Resource'),
        ),
        migrations.RemoveField(
            model_name='suite',
            name='Resource',
        ),
        migrations.AddField(
            model_name='suite',
            name='Resource',
            field=models.ManyToManyField(null=True, to='repository.Resource'),
        ),
    ]
