# Generated by Django 3.0.5 on 2021-01-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_auto_20210112_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='suite',
            name='create_time',
            field=models.DateTimeField(null=True, verbose_name='创建时间'),
        ),
    ]
