# Generated by Django 3.0.5 on 2021-01-12 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20210112_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='repository.Project'),
            preserve_default=False,
        ),
    ]
