# Generated by Django 3.0.5 on 2021-01-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20210112_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='sort',
            field=models.IntegerField(null=True, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='project',
            field=models.ForeignKey(on_delete=models.SET(1), to='repository.Project'),
        ),
        migrations.RemoveField(
            model_name='suite',
            name='Resource',
        ),
        migrations.AddField(
            model_name='suite',
            name='Resource',
            field=models.CharField(default=None, max_length=128, verbose_name='引用资源'),
            preserve_default=False,
        ),
    ]
