# Generated by Django 3.0.5 on 2021-01-16 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20210114_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword_name', models.CharField(max_length=32, unique=True, verbose_name='关键字名称')),
                ('Documentation', models.CharField(max_length=255, verbose_name='关键字描述')),
                ('Arguments', models.CharField(max_length=128, verbose_name='参数')),
                ('Teardown', models.CharField(max_length=128, verbose_name='还原操作')),
                ('Return_Value', models.CharField(max_length=128, verbose_name='返回结果')),
                ('Timeout', models.CharField(max_length=32, verbose_name='超时时间')),
                ('Tags', models.CharField(max_length=128, verbose_name='标识')),
                ('Table_value', models.TextField(max_length=255, verbose_name='关键字内容')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('Resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Resource')),
            ],
        ),
    ]
