# Generated by Django 3.0.5 on 2021-01-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_keyword'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='keyword',
            table='keyword',
        ),
    ]
