# Generated by Django 3.0.5 on 2021-01-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_auto_20210118_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='Resource',
            new_name='resource',
        ),
    ]
