# Generated by Django 3.0.5 on 2021-01-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_auto_20210119_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_name',
            field=models.CharField(max_length=32, verbose_name='关键字名称'),
        ),
    ]
