# Generated by Django 3.0.5 on 2021-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_auto_20210119_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='suite_name',
            field=models.CharField(max_length=32, verbose_name='套件名称'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='testcase_name',
            field=models.CharField(max_length=32, verbose_name='用例名称'),
        ),
    ]
