# Generated by Django 3.0.5 on 2021-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20210119_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='Documentation',
            field=models.CharField(max_length=255, verbose_name='用例描述'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Setup',
            field=models.CharField(max_length=128, verbose_name='初始化'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='Table_value',
            field=models.TextField(max_length=255, verbose_name='用例内容'),
        ),
        migrations.AlterUniqueTogether(
            name='suite',
            unique_together={('project', 'suite_name')},
        ),
    ]
