# Generated by Django 3.0.5 on 2021-01-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_auto_20210119_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='Temple',
            new_name='Template',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='Return_Value',
        ),
    ]
