# Generated by Django 3.0.5 on 2021-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20210119_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('library_name', models.CharField(max_length=32, verbose_name='库名称')),
                ('documentation', models.CharField(max_length=255, verbose_name='方法描述')),
                ('class_name', models.CharField(max_length=128, verbose_name='类名称')),
                ('method_name', models.CharField(max_length=128, verbose_name='还原操作')),
                ('filepath', models.CharField(max_length=32, verbose_name='超时时间')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'library',
            },
        ),
    ]
