# Generated by Django 3.0.5 on 2021-01-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0018_auto_20210125_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_name',
            field=models.CharField(max_length=32, verbose_name='资源名称'),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('project', 'resource_name')},
        ),
    ]
