# Generated by Django 3.0.5 on 2021-01-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_auto_20210126_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='Documentation',
            field=models.TextField(verbose_name='关键字描述'),
        ),
    ]
