# Generated by Django 3.0.5 on 2021-01-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0020_auto_20210128_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_name',
            field=models.CharField(max_length=128, verbose_name='关键字名称'),
        ),
    ]
