# Generated by Django 3.0.5 on 2021-01-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0021_auto_20210128_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='method_name',
            field=models.CharField(max_length=1000, verbose_name='函数名称'),
        ),
    ]
