# Generated by Django 3.0.5 on 2021-01-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0022_auto_20210128_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='method_name',
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=128, verbose_name='方法名称')),
                ('documentation', models.CharField(max_length=255, null=True, verbose_name='方法描述')),
                ('Arguments', models.CharField(max_length=128, verbose_name='参数')),
                ('Return_Value', models.CharField(max_length=128, verbose_name='返回结果')),
                ('create_time', models.DateTimeField(null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(null=True, verbose_name='修改时间')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Suite')),
            ],
            options={
                'db_table': 'method',
            },
        ),
    ]
