# Generated by Django 3.0.5 on 2021-01-30 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0023_auto_20210130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Library'),
        ),
    ]
