# Generated by Django 3.0.5 on 2021-01-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0024_auto_20210130_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='documentation',
            field=models.TextField(null=True, verbose_name='方法描述'),
        ),
        migrations.AlterField(
            model_name='method',
            name='documentation',
            field=models.TextField(null=True, verbose_name='方法描述'),
        ),
    ]
