# Generated by Django 3.0.5 on 2021-02-01 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0025_auto_20210130_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='Arguments',
            field=models.CharField(max_length=255, verbose_name='参数'),
        ),
    ]
