# Generated by Django 3.0.5 on 2021-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0027_auto_20210201_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('documentation', models.TextField(verbose_name='任务内容')),
                ('status', models.CharField(max_length=128, verbose_name='任务状态')),
                ('user', models.CharField(max_length=128, verbose_name='执行人')),
                ('start_time', models.DateTimeField(null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(null=True, verbose_name='结束时间')),
                ('take_time', models.CharField(max_length=128, null=True, verbose_name='耗时')),
                ('report_path', models.CharField(max_length=128, null=True, verbose_name='详细报告')),
                ('log_path', models.CharField(max_length=128, null=True, verbose_name='实时日志')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
