# Generated by Django 3.0.5 on 2021-02-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0028_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.Project'),
        ),
    ]
