# Generated by Django 3.0.5 on 2021-02-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0029_auto_20210207_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repository.Project'),
        ),
    ]
