# Generated by Django 3.0.5 on 2021-02-10 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0032_auto_20210209_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger',
            old_name='trigger_status',
            new_name='enable',
        ),
    ]
