# Generated by Django 3.0.5 on 2021-02-19 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0035_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repository.UserInfo'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='repository.UserInfo'),
        ),
    ]
