# Generated by Django 3.0.5 on 2021-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0037_auto_20210222_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smtp',
            name='mail_host',
            field=models.CharField(max_length=64, verbose_name='邮箱地址'),
        ),
    ]
